# Generated by Django 2.0.5 on 2018-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_date', models.DateTimeField()),
                ('category1', models.IntegerField()),
                ('category2', models.IntegerField()),
                ('Place', models.CharField(max_length=100)),
                ('Payment', models.IntegerField()),
                ('Summary', models.CharField(max_length=100)),
            ],
        ),
    ]
