# Generated by Django 2.0.5 on 2018-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Summary',
            new_name='summary',
        ),
    ]
